# Generated by Django 3.1.6 on 2021-03-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_planner', '0003_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(blank=True, help_text='Separate them with ; '),
        ),
    ]
