# Generated by Django 3.1.6 on 2021-03-28 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_planner', '0004_auto_20210328_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 11, 1, 6, 22390)),
        ),
    ]
