# Generated by Django 3.1.6 on 2021-03-28 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_planner', '0008_auto_20210328_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrition',
            name='name',
        ),
        migrations.AddField(
            model_name='nutrition',
            name='value',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 12, 40, 57, 225345)),
        ),
    ]
