# Generated by Django 3.1.6 on 2021-03-28 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_planner', '0016_auto_20210328_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='receipe',
        ),
        migrations.AddField(
            model_name='test',
            name='value',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 12, 50, 18, 744155)),
        ),
    ]
