# Generated by Django 3.1.6 on 2021-03-28 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_planner', '0018_auto_20210328_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 12, 56, 29, 584163)),
        ),
    ]
