# Generated by Django 3.1.6 on 2021-03-28 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_planner', '0019_auto_20210328_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 12, 56, 48, 101763)),
        ),
    ]
