# Generated by Django 3.1.6 on 2021-03-28 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_planner', '0020_auto_20210328_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutrition',
            old_name='value',
            new_name='grams',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 12, 57, 7, 961352)),
        ),
    ]
