# Generated by Django 3.1.6 on 2021-03-28 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_planner', '0029_auto_20210328_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='title',
        ),
    ]
