# Generated by Django 3.1.6 on 2021-03-28 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_planner', '0034_recipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
