# Generated by Django 3.1.6 on 2021-03-28 12:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_planner', '0036_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='title',
            field=models.CharField(default='Default', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='content',
            field=ckeditor.fields.RichTextField(default='Default'),
            preserve_default=False,
        ),
    ]
