# Generated by Django 3.1.6 on 2021-03-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_planner', '0038_auto_20210328_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='categories',
            field=models.CharField(blank=True, help_text='Separate categories with ;', max_length=120, null=True),
        ),
    ]
