# Generated by Django 3.1.6 on 2021-03-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_planner', '0041_nutrition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='name',
            field=models.CharField(choices=[('kcal', 'kcal'), ('fat', 'fat'), ('saturates', 'saturates'), ('carbs', 'carbs'), ('sugars', 'sugars'), ('fibre', 'fibre'), ('salt', 'salt'), ('protein', 'frotein')], max_length=255),
        ),
    ]
