# Generated by Django 3.1.6 on 2021-03-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_planner', '0042_auto_20210328_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='name',
            field=models.CharField(choices=[('kcal', 'Kcal'), ('fat', 'Fat'), ('saturates', 'Saturates'), ('carbs', 'Carbs'), ('sugars', 'Sugars'), ('fibre', 'Fibre'), ('salt', 'Salt'), ('protein', 'Protein')], max_length=255),
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='recipe',
        ),
        migrations.AddField(
            model_name='nutrition',
            name='recipe',
            field=models.ManyToManyField(to='nutrition_planner.Recipe'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='value',
            field=models.FloatField(help_text='In grams', null=True),
        ),
    ]
