# Generated by Django 3.1.6 on 2021-03-28 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_planner', '0043_auto_20210328_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrition',
            name='recipe',
        ),
        migrations.AddField(
            model_name='nutrition',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='nutrition_planner.recipe'),
        ),
    ]
