# Generated by Django 3.1.6 on 2021-03-28 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_planner', '0045_auto_20210328_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cook_time',
        ),
    ]
