# Generated by Django 3.1.6 on 2021-03-28 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_planner', '0048_recipe_serving'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='serving',
            new_name='servings',
        ),
    ]
