# Generated by Django 3.1.6 on 2021-03-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='thumbnail',
            field=models.ImageField(default='exercise-default.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='exercise',
            name='video_url',
            field=models.URLField(null=True),
        ),
    ]
