# Generated by Django 3.1.6 on 2021-03-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_auto_20210331_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='acreditations',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
