# Generated by Django 3.1.6 on 2021-03-31 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_exercise_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='acreditations',
            new_name='image_source',
        ),
    ]
