# Generated by Django 3.1.6 on 2021-03-26 23:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep_tracker', '0002_auto_20210326_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleep',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 26, 23, 6, 23, 609844)),
        ),
        migrations.AddField(
            model_name='sleep',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 26, 23, 6, 23, 609811)),
        ),
    ]
