# Generated by Django 3.1.6 on 2021-04-01 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sleep_tracker', '0069_auto_20210331_1516'),
        ('sleep_tracker', '0069_auto_20210331_0249'),
    ]

    operations = [
    ]
