# Generated by Django 3.1.6 on 2021-04-01 23:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep_tracker', '0071_auto_20210402_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleep',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 2, 0, 40, 27, 402516)),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 2, 0, 40, 27, 402490)),
        ),
    ]
