# Generated by Django 3.1.6 on 2021-04-02 00:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep_tracker', '0073_auto_20210402_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleep',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 2, 1, 6, 54, 983119)),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 2, 1, 6, 54, 983094)),
        ),
    ]
