# Generated by Django 3.1.6 on 2021-04-02 02:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep_tracker', '0075_auto_20210402_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleep',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 2, 3, 39, 59, 274534)),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 2, 3, 39, 59, 274487)),
        ),
    ]
