# Generated by Django 3.1.6 on 2021-04-01 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='comment',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
