# Generated by Django 3.1.6 on 2021-04-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_tracker', '0005_auto_20210402_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='comment',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='emotion',
            field=models.CharField(choices=[('happy', 'Happy'), ('excited', 'Excited'), ('angry', 'Angry'), ('sad', 'Sad')], default='Unspecified', max_length=300, verbose_name='How do you feel'),
        ),
    ]
